### ISSUE TITLE
 How to set up a multinode local private chain with EVM parallel mechanism?

### ISSUE THREAD

**Issue by sdjasj** [sei-protocol/sei-chain#1383]
**Seid version**
name: sei
server_name: <appd>
version: v4.1.4-evm-devnet
commit: 6e26498471079268799dd14091ca7256680cb82f
build_tags: netgo ledger,
go: go version go1.22.0 linux/amd64
build_deps:
- cosmossdk.io/errors@v1.0.0
- filippo.io/edwards25519@v1.0.0-rc.1
- github.com/99designs/keyring@v1.2.1

**Chain ID**
None

**Describe the Issue**
I start four nodes using `make docker-cluster-start` and then want to deploye an EVM contract following https://v2.docs.sei.io/quickstart/nft-contract-tutorial. However, when executing 'forge create --rpc-url https://localhost:8545 --private-key <your_private_key> src/MyNFT.sol:MyNFT', I am unsure how to generate the private_key and receive an airdrop.

Now my questions are:
1. How to generate a private key supported by SEI?
2. How to receive an airdrop to have enough funds for deploying the contract locally?
3. Are the steps I followed correct?

I appreciate any assistance. Thank you!

**Additional context**

**Comment by farazsth98** [comment]
1. Since you're already using foundry, use `cast wallet new` to create a new private key that you can use.
2. Within the node, there is an `send` command. If you do a `seid keys list` in the `sei-node-0` container, it will list all the keys. Use the admin's key with this command to send your new wallet (created in the previous step) some funds: https://github.com/sei-protocol/sei-chain/blob/v4.1.4-evm-devnet/x/evm/client/cli/tx.go#L151
3. I guess? Are the nodes running correctly? Can you interact with the EVM chain?
