### ISSUE TITLE
Benchmarking methodology

### ISSUE THREAD

**Issue by outofforest** [sei-protocol/sei-chain#728]
Hi team!

Could you please describe the methodology used to measure the 20k orders per second throughput?
- How many validators,s entries and full nodes were created?
- Where were they created?
- What machines were used?
- What was the network topology?
- How many clients were used to broadcast the transactions?

Also I would like to understand what do you mean exactly by saying that 20k orders per second are processed?
- Do you mean that single transaction is executed per order?
- Or maybe many messages are processed in single transaction?
- Does one transaction/message contain a single order or there are many orders in single transaction/message?
- Let's say that there is a logic which matches two orders (buy & sell). Do you count it as two orders in the "20k" result or as a single action?

Thanks in advance!

**Comment by philipsu522** [comment]
Hey @outofforest, thanks for the question!
How many validators,s entries and full nodes were created? 
**We did benchmark with 35 validator nodes. No full nodes were created as part of the benchmark since they were**
Where were they created? 
**They were dispersed among various regions. An example breakdown would be:
Ohio - 5
Sydney - 6
Seoul - 6
Frankfurt - 6
Sao Paulo - 6
Cape Town - 6**
What machines were used?
**16CPU, 64GB mem**
What was the network topology?
**We had all nodes set each other as persistent peers (connected graph)**
How many clients were used to broadcast the transactions?
**we used up to 1000 clients (the number changed based on how large batch size was)**
Do you mean that single transaction is executed per order?
**We did tests on both single and batched txs**
Or maybe many messages are processed in single transaction?
**Answered above**
Does one transaction/message contain a single order or there are many orders in single transaction/message?
**Answered above**
Let's say that there is a logic which matches two orders (buy & sell). Do you count it as two orders in the "20k" result or as a single action?
**This would be counted as multiple txs since it does result in 2 txs committed to the chain**

**Comment by philipsu522** [comment]
Feel free to reopen if you have more questions - happy to chat!
