### ISSUE TITLE
[BUG] Unable to run validator node.

### ISSUE THREAD

**Issue by Shariful999** [sei-protocol/sei-chain#847]
Can somebody help to figure out what we should do here to fix the issue?  Stuck somehow here. Couldn’t find any support on Discord. 

![Screenshot (56)](https://github.com/sei-protocol/sei-chain/assets/54259620/d0a62eeb-41de-4ab4-91d6-a8c8946af745)
![Screenshot (55)](https://github.com/sei-protocol/sei-chain/assets/54259620/803832d4-9aca-417f-9907-bdc8cd7b7d74)

**Comment by yzang2019** [comment]
Can you provide more context of what you are trying to do here? Run a validator node locally? Or join an existing testnet?

**Comment by Shariful999** [comment]
Hi I'm trying to join existing testnet - Atlantic 2 testnet. Trying to run validator node there. 

https://app.nodejumper.io/sei-testnet/sync I was following this guide and stuck with the following code 

sed -i 's|^mode = "full"|mode = "validator"|g' $HOME/.sei/config/config.toml
seid tx staking create-validator \
--amount=1000000usei \
--pubkey=$(seid tendermint show-validator) \
--moniker="$NODE_MONIKER" \
--chain-id=atlantic-2 \
--commission-rate=0.1 \
--commission-max-rate=0.2 \
--commission-max-change-rate=0.05 \
--min-self-delegation=1 \
--from=wallet \
-y

It doesn’t work to setup the validator. I'm just a new guy with little bit coding understanding. Any help is highly appreciated 🙏

**Comment by Shariful999** [comment]
@philipsu522 @yzang2019

**Comment by philipsu522** [comment]
@Shariful999 have you checked out https://docs.sei.io/full-node/run-a-sei-node yet? Most folks are able to get things working with those instructions. If you're still having issues, please follow up in our Discord server (https://discord.gg/sei).  Github issues might not be the best place to do this. Github issues are more relevant for actual bugs in the code rather than debugging help.
