### ISSUE TITLE
[BREAKING BUG] Atlantic-2 RPC url sends a 403 Forbidden after the first interaction with it

### ISSUE THREAD

**Issue by vscorpio** [sei-protocol/sei-chain#946]
**Seid version**
Irrelevant

**Chain ID**
`atlantic-2`

**Describe the bug**
The `atlantic-2` testnet RPC URL (https://rpc.atlantic-2.seinetwork.io/) sends out a 403 Forbideden response every few minutes. The RPC seems to work just fine. When interacting with it to read/write something to the blockchain (perform a query or an execute function) it executes fine, only to have a very high chance of going down for minuts at a time. Is it rate limited in any way? if yes, what is the maximum requests per minute? If it is rate limited then the response should not be **503**.

**To Reproduce**
1. Try to use it

Also, why is there the Developers Group - people who build on Sei so hard to get into? It should be public. Are you not willing to incentivize people to build on your chain, discussing stuff while they're at it?

**Expected behavior**
To work continuously, without going down every once in a while for minutes at a time.

**Comment by yzang2019** [comment]
@vscorpio Yes, this RPC behind a rate limiter, we are not able to give more details about the rate limiting tule, but if you got forbidden, it's mostly likely due to rate limiting, it might also be when we do have some bad rpc instances, which should be fixed now. Do you mind trying that again and let me know if you can consistently repro it?

**Comment by vscorpio** [comment]
The issue seems to have been resolved. If still occuring, it doesn’t do so with a high enough frequency to be bothered by it.
