### ISSUE TITLE
Particle smart contract problem in the example

### ISSUE THREAD

**Issue by onebyoneby** [sei-protocol/sei-chain#988]
There is a counter address in the example
![image](https://github.com/sei-protocol/sei-chain/assets/50565415/848fb750-c5a8-4940-8aeb-313d49aa2e35)
This is my result
![image](https://github.com/sei-protocol/sei-chain/assets/50565415/644438eb-9ff3-41b7-ba73-ef451597e006)
Executing the next step will report an error
![image](https://github.com/sei-protocol/sei-chain/assets/50565415/b29d8a03-3674-400a-860d-1bfde47954bb)
please,hlep me

**Comment by Kbhat1** [comment]
@onebyoneby there are two issues here. 

(1) Can you send me whats in your `increment.sh`? You need to add the address of the contract to the `contract` line as mentioned:
```
contract='' # Fill in contract address from deployment step, ex. sei14hj2tavq8fpesdwxxcu44rty3hh90vhujrvcmstl4zr3txmfvw9sh9m79m
```
(2) It seems like the original issue is that your contract wasn't properly instantiated since the deployed counter address is empty. Specifically this step likely had an issue: ```
addr=$(printf $password |$seid tx wasm instantiate $code '{"count": 0}' --from $keyname --broadcast-mode=block --label "counter" --chain-id sei-chain --gas=30000000 --fees=300000usei --admin=$admin_addr -y | grep -A 1 -m 1 "key: _contract_address" | sed -n 's/.*value: //p' | xargs)```

Can you run `seid q wasm list-contract-by-code 4` and send the output here? If that doesn't show anything could you re run the commands in in deploy.sh but replace the line above with just `seid tx wasm instantiate $code '{"count": 0}' --from $keyname --broadcast-mode=block --label "counter" --chain-id sei-chain --gas=30000000 --fees=300000usei --admin=$admin_addr -y`. Please send the output there which will show if there was an error during instantiation.

Let me know if there are any questions
